name: Run import_data script

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose branch'
        required: true
        default: 'main'

jobs:
  Run_import_data_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: test wkdir
      run: ls -lR embedding_model/danishbert-cosine-embeddings

    - name: Run import_data.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python import_data.py
